from collections.abc import Callable
from typing import Optional

class TokenBucket:
    def __init__(self, capacity: int, refill_per_sec: int, *, time_source: Optional[Callable[[], float]] = ...) -> None: ...
    def acquire(self, n: int = ...) -> bool: ...
    def remaining(self) -> int: ...

class SlidingWindow:
    def __init__(self, max_events: int, window_ms: int, *, time_source: Optional[Callable[[], float]] = ...) -> None: ...
    def try_add(self) -> bool: ...
